import { Inter } from "next/font/google";
import "./globals.css";
import SidebarLayouts from "./components/UI/SidebarLayouts/SidebarLayouts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarLayouts>{children}</SidebarLayouts>
      </body>
    </html>
  );
}
