export const people = [
  {
    name: "Илья Сергеевич Гриненко",
    role: "#",
    imageUrl: "/chempions/doska/Илья Сергеевич Гриненко.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  { 
    name: "Антип Бачурин",
    role: "#",
    imageUrl: "/chempions/doska/Антип Бачурин.JPG",
    bio: "Тренер по тайскому боксу.",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Екатерина Бежан",
    role: "#",
    imageUrl: "/chempions/doska/Екатерина Бежан.JPG",
    bio: "Тренер по тайскому боксу.",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Александра Костромцова",
    role: "#",
    imageUrl: "/chempions/doska/Александра Костромцова.jpg",
    bio: "Тренер",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Антон Азаркин",
    role: "#",
    imageUrl: "/chempions/doska/Антон Азаркин.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  }, 
  {
    name: "Андрей Акуленко",
    role: "#",
    imageUrl: "/chempions/doska/Антон Азаркин.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Стас Рутковский",
    role: "#",
    imageUrl: "/chempions/doska/Стас Рутковский.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Андрей Акуленко",
    role: "#",
    imageUrl: "/chempions/1.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Андрей Акуленко",
    role: "#",
    imageUrl: "/chempions/1.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Андрей Акуленко",
    role: "#",
    imageUrl: "/chempions/1.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Андрей Акуленко",
    role: "#",
    imageUrl: "/chempions/1.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Андрей Акуленко",
    role: "#",
    imageUrl: "/chempions/1.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  // More people...
];
