export const people = [
  {
    name: "Илья Сергеевич Гриненко",
    role: "#",
    imageUrl: "/chempions/doska/Илья Сергеевич Гриненко.jpg",
    bio: "Президент,Тренер,Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  { 
    name: "Антип Бачурин",
    role: "#",
    imageUrl: "/chempions/doska/Антип Бачурин.JPG",
    bio: "Тренер по тайскому боксу.",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Екатерина Бежан",
    role: "#",
    imageUrl: "/chempions/doska/Екатерина Бежан.JPG",
    bio: "Тренер по тайскому боксу.",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Александра Костромцова",
    role: "#",
    imageUrl: "/chempions/doska/Александра Костромцова.jpg",
    bio: "Тренер",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Антон Азаркин",
    role: "#",
    imageUrl: "/chempions/doska/Антон Азаркин.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  }, 
  {
    name: "Даниил Борисенко",
    role: "#",
    imageUrl: "/chempions/doska/Даниил Борисенко.jpg",
    bio: "Тренер клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Стас Рутковский",
    role: "#",
    imageUrl: "/chempions/doska/Стас Рутковский.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Руслана Гараева",
    role: "#",
    imageUrl: "/chempions/doska/Руслана Гараева.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Риана Каравалиева",
    role: "#",
    imageUrl: "/chempions/doska/Риана Каравалиева.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Сархан Акберов",
    role: "#",
    imageUrl: "/chempions/doska/Сархан Акберов.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Каролина Петрова",
    role: "#",
    imageUrl: "/chempions/doska/Каролина Петрова.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Анвар Раджабов",
    role: "#",
    imageUrl: "/chempions/doska/Анвар Раджабов.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Богдан Гусев",
    role: "#",
    imageUrl: "/chempions/doska/Богдан Гусев.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Богдан Паньков",
    role: "#",
    imageUrl: "/chempions/doska/Богдан Паньков.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Виктория Плаксина",
    role: "#",
    imageUrl: "/chempions/doska/Виктория Плаксина.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Дима Скорняков",
    role: "#",
    imageUrl: "/chempions/doska/Дима Скорняков.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  {
    name: "Ева Лала",
    role: "#",
    imageUrl: "/chempions/doska/Ева Лала.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },{
    name: "Лера Рутковская",
    role: "#",
    imageUrl: "/chempions/doska/Лера Рутковская.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },{
    name: "Мансур Рамазанов",
    role: "#",
    imageUrl: "/chempions/doska/Мансур Рамазанов.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },{
    name: "Маша Нечаева",
    role: "#",
    imageUrl: "/chempions/doska/Маша Нечаева.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },{
    name: "Никита Алексеев",
    role: "#",
    imageUrl: "/chempions/doska/Никита Алексеев.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },{
    name: "Никита Плешков",
    role: "#",
    imageUrl: "/chempions/doska/Никита Плешков.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },{
    name: "Ратмир Гусев",
    role: "#",
    imageUrl: "/chempions/doska/Ратмир Гусев.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },{
    name: "Тунар Аббасов",
    role: "#",
    imageUrl: "/chempions/doska/Тунар Аббасов.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },{
    name: "Эльмир Алиев",
    role: "#",
    imageUrl: "/chempions/doska/Эльмир Алиев.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },{
    name: "Эвелина Назмутдинова",
    role: "#",
    imageUrl: "/chempions/doska/Эвелина Назмутдинова.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },{
    name: "Ксения",
    role: "#",
    imageUrl: "/chempions/doska/Ксения.jpg",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },{
    name: "Андрей Акуленко",
    role: "#",
    imageUrl: "/chempions/doska/",
    bio: "Боец клуба Югра",
    InstagramUrl: "#",
    VKUrl: "#",
  },
  // More people...
];
