const scheduleTraining = {
  1: [
    {
      key: 1.1,
      time: "9:00 - 10:30",
      title: "Тайский бокс - спорстмены",
      trainerId: 3,
    },
    {
      key: 1.2,
      time: "10:00 - 11:30",
      title: "Тайский бокс",
      trainerId: 4,
    },
    {
      key: 1.3,
      time: "15:00 - 16:30",
      title: "Тайский бокс",
      trainerId: 5,
    },
    {
      key: 1.4,
      time: "16:30 - 18:00",
      title: "Тайский бокс",
      trainerId: 6,
    },
    {
      key: 1.5,
      time: "18:00 - 19:30",
      title: "Кикбоксинг",
      trainerId: 7,
    },
    {
      key: 1.6,
      time: "19:30 - 21:00",
      title: "Тайский бокс",
      trainerId: 8,
    },
    {
      key: 1.7,
      time: "21:00 - 22:30",
      title: "Тайский бокс",
      trainerId: 9,
    },
    {
      key: 1.8,
      time: "22:30 - 00:00",
      title: "Тайский бокс",
      trainerId: 1,
    },
    {
      key: 1.9,
      time: "00:00 - 01:30",
      title: "Тайский бокс",
      trainerId: 2,
    },
  ],
  2: [
    {
      key: 1.1,
      time: "9:00 - 10:30",
      title: "Тайский бокс - спорстмены",
      trainerId: 3,
    },
    {
      key: 1.2,
      time: "10:00 - 11:30",
      title: "Тайский бокс",
      trainerId: 4,
    },
    {
      key: 1.3,
      time: "15:00 - 16:30",
      title: "Тайский бокс",
      trainerId: 5,
    },
    {
      key: 1.4,
      time: "16:30 - 18:00",
      title: "Тайский бокс",
      trainerId: 6,
    },
    {
      key: 1.5,
      time: "18:00 - 19:30",
      title: "Кикбоксинг",
      trainerId: 7,
    },
    {
      key: 1.6,
      time: "19:30 - 21:00",
      title: "Тайский бокс",
      trainerId: 8,
    },
    {
      key: 1.7,
      time: "21:00 - 22:30",
      title: "Тайский бокс",
      trainerId: 9,
    },
    {
      key: 1.8,
      time: "22:30 - 00:00",
      title: "Тайский бокс",
      trainerId: 1,
    },
    {
      key: 1.9,
      time: "00:00 - 01:30",
      title: "Тайский бокс",
      trainerId: 2,
    },
  ],
  3: [
    {
      key: 1.1,
      time: "9:00 - 10:30",
      title: "Тайский бокс - спорстмены",
      trainerId: 3,
    },
    {
      key: 1.2,
      time: "10:00 - 11:30",
      title: "Тайский бокс",
      trainerId: 4,
    },
    {
      key: 1.3,
      time: "15:00 - 16:30",
      title: "Тайский бокс",
      trainerId: 5,
    },
    {
      key: 1.4,
      time: "16:30 - 18:00",
      title: "Тайский бокс",
      trainerId: 6,
    },
    {
      key: 1.5,
      time: "18:00 - 19:30",
      title: "Кикбоксинг",
      trainerId: 7,
    },
    {
      key: 1.6,
      time: "19:30 - 21:00",
      title: "Тайский бокс",
      trainerId: 8,
    },
    {
      key: 1.7,
      time: "21:00 - 22:30",
      title: "Тайский бокс",
      trainerId: 9,
    },
    {
      key: 1.8,
      time: "22:30 - 00:00",
      title: "Тайский бокс",
      trainerId: 1,
    },
    {
      key: 1.9,
      time: "00:00 - 01:30",
      title: "Тайский бокс",
      trainerId: 2,
    },
  ],
  4: [
    {
      key: 1.1,
      time: "9:00 - 10:30",
      title: "Тайский бокс - спорстмены",
      trainerId: 3,
    },
    {
      key: 1.2,
      time: "10:00 - 11:30",
      title: "Тайский бокс",
      trainerId: 4,
    },
    {
      key: 1.3,
      time: "15:00 - 16:30",
      title: "Тайский бокс",
      trainerId: 5,
    },
    {
      key: 1.4,
      time: "16:30 - 18:00",
      title: "Тайский бокс",
      trainerId: 6,
    },
    {
      key: 1.5,
      time: "18:00 - 19:30",
      title: "Кикбоксинг",
      trainerId: 7,
    },
    {
      key: 1.6,
      time: "19:30 - 21:00",
      title: "Тайский бокс",
      trainerId: 8,
    },
    {
      key: 1.7,
      time: "21:00 - 22:30",
      title: "Тайский бокс",
      trainerId: 9,
    },
    {
      key: 1.8,
      time: "22:30 - 00:00",
      title: "Тайский бокс",
      trainerId: 1,
    },
    {
      key: 1.9,
      time: "00:00 - 01:30",
      title: "Тайский бокс",
      trainerId: 2,
    },
  ],
  5: [
    {
      key: 1.1,
      time: "9:00 - 10:30",
      title: "Тайский бокс - спорстмены",
      trainerId: 3,
    },
    {
      key: 1.2,
      time: "10:00 - 11:30",
      title: "Тайский бокс",
      trainerId: 4,
    },
    {
      key: 1.3,
      time: "15:00 - 16:30",
      title: "Тайский бокс",
      trainerId: 5,
    },
    {
      key: 1.4,
      time: "16:30 - 18:00",
      title: "Тайский бокс",
      trainerId: 6,
    },
    {
      key: 1.5,
      time: "18:00 - 19:30",
      title: "Кикбоксинг",
      trainerId: 7,
    },
    {
      key: 1.6,
      time: "19:30 - 21:00",
      title: "Тайский бокс",
      trainerId: 8,
    },
    {
      key: 1.7,
      time: "21:00 - 22:30",
      title: "Тайский бокс",
      trainerId: 9,
    },
    {
      key: 1.8,
      time: "22:30 - 00:00",
      title: "Тайский бокс",
      trainerId: 1,
    },
    {
      key: 1.9,
      time: "00:00 - 01:30",
      title: "Тайский бокс",
      trainerId: 2,
    },
  ],
  6: [
    {
      key: 1.1,
      time: "9:00 - 10:30",
      title: "Тайский бокс - спорстмены",
      trainerId: 3,
    },
    {
      key: 1.2,
      time: "10:00 - 11:30",
      title: "Тайский бокс",
      trainerId: 4,
    },
    {
      key: 1.3,
      time: "15:00 - 16:30",
      title: "Тайский бокс",
      trainerId: 5,
    },
    {
      key: 1.4,
      time: "16:30 - 18:00",
      title: "Тайский бокс",
      trainerId: 6,
    },
    {
      key: 1.5,
      time: "18:00 - 19:30",
      title: "Кикбоксинг",
      trainerId: 7,
    },
    {
      key: 1.6,
      time: "19:30 - 21:00",
      title: "Тайский бокс",
      trainerId: 8,
    },
    {
      key: 1.7,
      time: "21:00 - 22:30",
      title: "Тайский бокс",
      trainerId: 9,
    },
    {
      key: 1.8,
      time: "22:30 - 00:00",
      title: "Тайский бокс",
      trainerId: 1,
    },
    {
      key: 1.9,
      time: "00:00 - 01:30",
      title: "Тайский бокс",
      trainerId: 2,
    },
  ],
  7: [
    {
      key: 1.1,
      time: "9:00 - 10:30",
      title: "Тайский бокс - спорстмены",
      trainerId: 3,
    },
    {
      key: 1.2,
      time: "10:00 - 11:30",
      title: "Тайский бокс",
      trainerId: 4,
    },
    {
      key: 1.3,
      time: "15:00 - 16:30",
      title: "Тайский бокс",
      trainerId: 5,
    },
    {
      key: 1.4,
      time: "16:30 - 18:00",
      title: "Тайский бокс",
      trainerId: 6,
    },
    {
      key: 1.5,
      time: "18:00 - 19:30",
      title: "Кикбоксинг",
      trainerId: 7,
    },
    {
      key: 1.6,
      time: "19:30 - 21:00",
      title: "Тайский бокс",
      trainerId: 8,
    },
    {
      key: 1.7,
      time: "21:00 - 22:30",
      title: "Тайский бокс",
      trainerId: 9,
    },
    {
      key: 1.8,
      time: "22:30 - 00:00",
      title: "Тайский бокс",
      trainerId: 1,
    },
    {
      key: 1.9,
      time: "00:00 - 01:30",
      title: "Тайский бокс",
      trainerId: 2,
    },
  ],
};

export default scheduleTraining;
